// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace storyboard
{
	public partial class ViewControllerC : UIViewController
	{
		public ViewControllerC (IntPtr handle) : base (handle)
		{
		}

		partial void dismissButton (NSObject sender)
		{
			this.DismissViewController(true,null);
		}
	}
}
