// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace storyboard
{
	public partial class ViewControllerB : UIViewController
	{
		public ViewControllerB (IntPtr handle) : base (handle)
		{
		}
	}
}
